// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    // Prisma Migrate/Seed 建议优先使用直连（Neon direct）
    // - DIRECT_URL: Neon direct connection string（推荐用于 migrate/seed）
    // - DATABASE_URL: Neon pooled / 本地 docker（回退）
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
